apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-trioapp-asia
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /manifests/trio-app/aperture-prod-east
    codefresh.io/product: demo-trioapp
spec:
  project: default
  source:
    path: manifests/trio-app/aperture-prod-east
    repoURL: https://github.com/NimRegev/DevOps.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: demo-ta-asia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
