apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-trioapp-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /manifests/trio-app/aperture-dev
    codefresh.io/product: demo-trioapp
spec:
  destination:
    name: 'demo-dev'
    namespace: demo-ta-dev
  source:
    path: manifests/trio-app/aperture-dev
    repoURL: 'https://github.com/aperture-sci/DevOps'
    targetRevision: main
    # plugin:
    #   name: kustomize-build-with-helm
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
